# Generated by Django 3.2.7 on 2021-11-08 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulator', '0002_auto_20211107_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='units',
            field=models.DecimalField(decimal_places=8, max_digits=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='value',
            field=models.DecimalField(decimal_places=8, max_digits=100),
        ),
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(max_length=5)),
                ('units', models.DecimalField(decimal_places=8, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Holdings',
            },
        ),
    ]
